name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      # Warning: will clobber manual changes while in draft
      - uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
